apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: {{ include "team-namespace.name" . }}
  labels:
    {{- include "team-namespace.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limits.default.cpu | quote }}
        memory: {{ .Values.limits.default.memory | quote }}
      defaultRequest:
        cpu: {{ .Values.limits.defaultRequest.cpu | quote }}
        memory: {{ .Values.limits.defaultRequest.memory | quote }}
      max:
        cpu: {{ .Values.limits.max.cpu | quote }}
        memory: {{ .Values.limits.max.memory | quote }}
