apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: {{ include "team-namespace.name" . }}
  labels:
    {{- include "team-namespace.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.cpu | quote }}
    requests.memory: {{ .Values.quota.memory | quote }}
    limits.cpu: {{ .Values.quota.cpu | quote }}
    limits.memory: {{ .Values.quota.memory | quote }}
    pods: {{ .Values.quota.pods | quote }}
    persistentvolumeclaims: {{ .Values.quota.pvc | quote }}
    services: {{ .Values.quota.services | quote }}
