apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voting-app.api.fullname" . }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  DATABASE_HOST: {{ include "voting-app.postgres.fullname" . | quote }}
  DATABASE_PORT: "5432"
  DATABASE_NAME: {{ .Values.postgres.auth.database | quote }}
