apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-app.api.fullname" . }}
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "voting-app.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "voting-app.api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
