{{- if .Values.flyway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: voting-flyway-sql
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: flyway
data:
{{- range $path, $bytes := .Files.Glob "flyway-sql/*.sql" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
