apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-test
  namespace: argocd
  finalizers:
    - argocd.argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/simonangel-fong/project-eks-argocd
    targetRevision: master
    path: argocd/apps/eso-test
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
